"use client";

import { Download } from "lucide-react";
import { Button } from "../ui/button";

const DownloadSummaryButton = ({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) => {
  const handleDownload = () => {
    const summaryContent = `# ${title}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}

${summaryText}

Original File: ${fileName}
Generated by SnapSumm`;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob); //creates a temporary url that points at our blob. This lets us download the file even though its not on a server

    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, "_")}.txt`;
    document.body.appendChild(link);
    link.click(); //triggers the download

    document.body.removeChild(link); //removes the invisible link from the page.
    URL.revokeObjectURL(url); //frees up memory by revoking the temporary url we created.
  };
  return (
    <Button className="h-8 px-3 bg-cyan-950" onClick={handleDownload}>
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
};

export default DownloadSummaryButton;
